package radius

/* =========================================================
 * RADIUS ATTRIBUTE MAP
 * ========================================================= */

var radiusAttributeMap = map[uint16]string{
	1:  "User-Name",
	2:  "User-Password",
	3:  "CHAP-Password",
	4:  "NAS-IP-Address",
	5:  "NAS-Port",
	6:  "Service-Type",
	7:  "Framed-Protocol",
	8:  "Framed-IP-Address",
	9:  "Framed-IP-Netmask",
	10: "Framed-Routing",
	11: "Filter-Id",
	12: "Framed-MTU",
	13: "Framed-Compression",
	14: "Login-IP-Host",
	15: "Login-Service",
	16: "Login-TCP-Port",
	18: "Reply-Message",
	19: "Callback-Number",
	20: "Callback-Id",
	22: "Framed-Route",
	23: "Framed-IPX-Network",
	24: "State",
	25: "Class",
	26: "Vendor-Specific",
	27: "Session-Timeout",
	28: "Idle-Timeout",
	29: "Termination-Action",
	30: "Called-Station-Id",
	31: "Calling-Station-Id",
	32: "NAS-Identifier",
	33: "Proxy-State",
	34: "Login-LAT-Service",
	35: "Login-LAT-Node",
	36: "Login-LAT-Group",
	37: "Framed-Appletalk-Link",
	38: "Framed-Appletalk-Network",
	39: "Framed-Appletalk-Zone",
	40: "Acct-Status-Type",
	41: "Acct-Delay-Time",
	42: "Acct-Input-Octets",
	43: "Acct-Output-Octets",
	44: "Acct-Session-Id",
	45: "Acct-Authentic",
	46: "Acct-Session-Time",
	47: "Acct-Input-Packets",
	48: "Acct-Output-Packets",
	49: "Acct-Terminate-Cause",
	50: "Acct-Multi-Session-Id",
	51: "Acct-Link-Count",
	52: "Acct-Input-Gigawords",
	53: "Acct-Output-Gigawords",
	55: "Event-Timestamp",
	56: "Egress-VLANID",
	57: "Ingress-Filters",
	58: "Egress-VLAN-Name",
	59: "User-Priority-Table",
	60: "CHAP-Challenge",
	61: "NAS-Port-Type",
	62: "Port-Limit",
	63: "Login-LAT-Port",
	64: "Tunnel-Type",
	65: "Tunnel-Medium-Type",
	66: "Tunnel-Client-Endpoint",
	67: "Tunnel-Server-Endpoint",
	68: "Acct-Tunnel-Connection",
	69: "Tunnel-Password",
	70: "ARAP-Password",
	71: "ARAP-Features",
	72: "ARAP-Zone-Access",
	73: "ARAP-Security",
	74: "ARAP-Security-Data",
	75: "Password-Retry",
	76: "Prompt",
	77: "Connect-Info",
	78: "Configuration-Token",
	79: "EAP-Message",
	80: "Message-Authenticator",
	81: "Tunnel-Private-Group-Id",
	82: "Tunnel-Assignment-Id",
	83: "Tunnel-Preference",
	84: "ARAP-Challenge-Response",
	85: "Acct-Interim-Interval",
	86: "Acct-Tunnel-Packets-Lost",
	87: "NAS-Port-Id",
	88: "Framed-Pool",
	89: "CUI",
	90: "Tunnel-Client-Auth-Id",
	91: "Tunnel-Server-Auth-Id",
	92: "NAS-Filter-Rule",
	94: "Originating-Line-Info",
	95: "NAS-IPv6-Address",
	96: "Framed-Interface-Id",
	97: "Framed-IPv6-Prefix",
	98: "Login-IPv6-Host",
	99: "Framed-IPv6-Route",
	100: "Framed-IPv6-Pool",
	101: "Error-Cause",
	102: "EAP-Key-Name",
	103: "Digest-Response",
	104: "Digest-Realm",
	105: "Digest-Nonce",
	106: "Digest-Response-Auth",
	107: "Digest-Nextnonce",
	108: "Digest-Method",
	109: "Digest-URI",
	110: "Digest-QOP",
	111: "Digest-Algorithm",
	112: "Digest-Entity-Body-Hash",
	113: "Digest-CNonce",
	114: "Digest-Nonce-Count",
	115: "Digest-Username",
	116: "Digest-Opaque",
	117: "Digest-Auth-Param",
	118: "Digest-AKA-AUTS",
	119: "Digest-Domain",
	120: "Digest-Stale",
	121: "Digest-HA1",
	122: "SIP-AOR",
	123: "Delegated-IPv6-Prefix",
	124: "MIP6-Feature-Vector",
	125: "MIP6-Home-Link-Prefix",
	126: "Operator-Name",
	127: "Location-Information",
	128: "Location-Data",
	129: "Basic-Location-Policy-Rules",
	130: "Extended-Location-Policy-Rules",
	131: "Location-Capable",
	132: "Requested-Location-Info",
}

/* =========================================================
 * LOOKUP FUNCTION (Go replacement of linear scan)
 * ========================================================= */

func GetRadiusAttributeName(attrType uint16) string {
	if name, ok := radiusAttributeMap[attrType]; ok {
		return name
	}
	return "Unknown-Attribute"
}