# =========================
# GENERAL SETTINGS
# =========================
# cgnat_file_path=/root/radius-parser/config/cgnat_rules.csv
# whitelist_file_path=/root/radius-parser/config/whitelist_info.csv
interface_name=dummy0
threads=2,4,6,8,10,12,14,16,18
extract_all=no
verbosity=3
caplen=3200
update_timeout=300 # 15 minutes
# bye_timeout=43200 # 12 hours(Not Implemented)
ring_buffer_size=1048576 # 1 GB

# =========================
# INPUT FILES
# =========================

# input_file=/root/radius-parser/out/radius-jul-31.pcap

# =========================
# RabbitMQ CONFIG
# =========================

rabbitmq_host=127.0.0.1
rabbitmq_port=5672
rabbitmq_user=radius_user
rabbitmq_password=radius_pass
rabbitmq_vhost=radius
rabbitmq_exchange=radius_exchange